FROM python:3.13-slim
# сначала идут установки, чтобы они кешировались,
WORKDIR /app
COPY requirements.txt app/

RUN pip install --no-cache-dir -r app/requirements.txt


COPY . /app


CMD ["python", "main.py"]